name: collect-all

on:
  schedule:
    - cron: "15 10 * * *"        # daily at 10:15 UTC (adjust if you like)
  push:
    branches: [ main ]           # ← ensure it also runs on pushes to main
    paths-ignore:
      - ".github/**"
      - "dist/**"
  workflow_dispatch: {}          # manual “Run workflow” button

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/requirements.txt

      - name: Run collector (writes data/*.csv + status.json)
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}   # ← add in repo secrets
          UPA_YEAR: "2025"
        run: |
          python agents/collect_cfbd_all.py
          echo "Generated files:" && ls -la data

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A data
          if git diff --cached --quiet; then
            echo "No data changes; skipping commit."
          else
            git commit -m "data update"
            git push
          fi