# .github/workflows/collect-all.yml
name: Agent Collect & Update CSVs (All FBS)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write

env:
  PYTHONUNBUFFERED: "1"
  TZ: America/Phoenix

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/requirements.txt
      - name: Run collector
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          SHEET_ID: ${{ vars.SHEET_ID }}
        run: python agents/collect_cfbd_all.py
      - name: Commit & Push changes (if any)
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add -A
          if git diff --cached --quiet; then echo "No changes"; else git commit -m "data update"; git push; fi

  build-and-deploy:
    needs: collect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Debug tree (sanity)
        run: |
          pwd
          ls -la

      - name: Install (root)
        run: npm ci || npm i
        working-directory: .

      - name: Build (root)
        run: npm run build
        working-directory: .

      - name: Copy data into build output
        run: |
          mkdir -p dist/data
          if [ -d data ]; then cp -R data/* dist/data/ || true; fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4