
name: Agent Collect & Update CSVs (All FBS)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: write
  pages: write
  id-token: write

env:
  PYTHONUNBUFFERED: "1"
  TZ: America/Phoenix

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/requirements.txt

      - name: (Optional) Write Google service account key
        if: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON != '' }}
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/sa.json" >> $GITHUB_ENV

      - name: Run collector
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          SHEET_ID: ${{ vars.SHEET_ID }}
        run: |
          python agents/collect_cfbd_all.py

      - name: Commit & Push changes (if any)
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(data): update CFBD-derived CSVs and status [skip ci]"
            git push
          fi

  build-and-deploy:
    needs: collect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci || npm i

      - name: Build (Vite from repo root)
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
