name: refresh-markets-live

on:
  schedule:
    - cron: '*/5 * * * 5,6'
  workflow_dispatch: {}

concurrency:
  group: refresh-markets-live
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/requirements.txt

      - name: Refresh live markets and scoreboard
        env:
          CFBD_BEARER_TOKEN: ${{ secrets.CFBD_BEARER_TOKEN }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python -m agents.jobs.refresh_markets_live

      - name: Commit SQLite database
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if git diff --quiet data/upa_data.sqlite; then
            echo "No database changes to commit."
            exit 0
          fi
          git add data/upa_data.sqlite
          git commit -m "chore: refresh live markets data [skip ci]"
          git push
