name: live-scores

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  UPA_YEAR: "2025"
  CACHE_ONLY: "0"
  CACHE_TTL_DAYS: "2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Fetch live scores (ESPN)
        run: |
          python agents/fetch_live_scores.py --year "${{ env.UPA_YEAR }}" --out "data/live_scores.csv"

      - name: Stage site (copy repo → _site)
        run: |
          rm -rf _site
          mkdir -p _site
          rsync -a --delete --exclude '.git*' --exclude '.github' ./ _site/
          # Ensure latest CSV is present in the Pages data dir
          mkdir -p _site/data
          cp -f data/live_scores.csv _site/data/live_scores.csv

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4