name: live-scores

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  workflow_run:
    workflows: ["deploy"]
    types: [completed]

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

# prevent Pages from getting two concurrent deploys
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Fetch live scores (ESPN)
        run: python agents/fetch_live_scores.py --out live_scores.csv

      # Pull the last good site bundle produced by the deploy workflow
      - name: Download last site bundle (from deploy)
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: deploy.yml
          workflow_conclusion: success
          name: site-bundle
          path: site
          if_no_artifact_found: fail

      - name: Inject live scores into site bundle
        run: |
          mkdir -p site/data
          cp live_scores.csv site/data/live_scores.csv
          echo "Injected live_scores.csv into site/data/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4